### ISSUE TITLE
IE: Persistent Placeholder

### ISSUE THREAD

**Issue by lorraineS** [tovic/tags-input-beautifier#5]
On IE11 if our input has a placeholder, the plugin will convert this placeholder into a string, this will create an unwanted behavior since the placeholder will become a tag.

`<input type="search" id="tags" placeholder=« My placeholder »>`

```
  config = {
    join: ', ', 
    max: 5,
    alert: false,
    update: function() {}
  };

  var foo = new TIB(document.querySelector('input[id="tags"]'), config);
  foo.create();
```

![capture d ecran 2017-05-03 a 12 03 00](https://cloud.githubusercontent.com/assets/6030502/25657325/950e6cfc-2ffd-11e7-9d7e-5849e0c01997.png)

A first idea to fix this is to add values: [''] in the config object. That fixes the problem but that creates a second one: the placeholder remains after a first tag is created.

```
  config = {
    join: ', ', 
    values: [''], // empty values
    max: 5,
    alert: false,
    update: function() {}
  };

```

![capture d ecran 2017-05-03 a 12 10 08 2](https://cloud.githubusercontent.com/assets/6030502/25657376/e9bef4a6-2ffd-11e7-88a2-bfa2f3a2c508.png)

The result on your demo: http://codepen.io/anon/pen/GmvgRp (IE11 or less !)

![capture d ecran 2017-05-03 a 12 22 39 2](https://cloud.githubusercontent.com/assets/6030502/25657424/20437934-2ffe-11e7-90de-055efa990c3a.png)

**Comment by tovic** [comment]
I&rsquo;m affraid that I can&rsquo;t fix this issue by myself due to the limitation of the environment. But currently, the placeholder itself is also just a fake placeholder that is generated by the `placeholder` attribute on a `contenteditable` element ([tags-input-beautifier.css#L47&L54](https://github.com/tovic/tags-input-beautifier/blob/b1ea5a1ec293f38460c4fcd781bb1e3785428e24/tags-input-beautifier.css#L47&L54)). Thinking that IE can convert pseudo elements into a valid form value seems impossible for me. I see that you are using something like _Google Material_ framework? Do you have some script that behaves like `placeholder` polyfill? If so, maybe that&rsquo;s the cause.

I can produce the second capture from my environment, but only for the first tag:

![t-i-b bug](https://cloud.githubusercontent.com/assets/1669261/25736176/7d55f802-319a-11e7-8fea-0980ab36e23d.gif)

**Comment by lorraineS** [comment]
No, i use my own styles. No framework. I will keep you informed if i find a fix. :)

**Comment by tovic** [comment]
Tested on IE11.

![t-i-b fix](https://cloud.githubusercontent.com/assets/1669261/25772525/6438579a-3297-11e7-9a09-fbbea8662348.gif)

**Comment by lorraineS** [comment]
The refactoring has caused a new problem.

There is a problem with Safari because of min-width. There is not enough space and it returns us to the line after 3 letters.

<img width="1440" alt="capture d ecran 2017-05-07 a 12 19 27" src="https://cloud.githubusercontent.com/assets/6030502/25780002/1040f810-3321-11e7-9016-16f400c8d401.png">
